name: Book Feedback
description: Report an issue or suggest an improvement
title: "[Feedback]: "
body:
  - type: dropdown
    attributes:
      label: Type of feedback
      options:
        - Typo or formatting issue
        - Content clarification
        - Conceptual question
        - Suggestion for improvement
  - type: input
    attributes:
      label: Chapter or page
      placeholder: e.g. DAX Without Fear
  - type: textarea
    attributes:
      label: Description
      placeholder: Please describe the issue or suggestion clearly.
